spring:
  application:
    name: admin-server
  cloud:
    config:
      enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://shangyong:loan@127.0.0.1:18000/eureka/,http://shangyong:loan@127.0.0.1:18001/eureka/
management.security.enabled: false